DEFAULT_HOST = '127.0.0.1'
DEFAULT_PORT = '8080'
DEFAULT_LISTENERS = 500
DEFAULT_RECV_MSG_SIZE = 1024
DEFAULT_ROOT_DIR = '/home/yaches/TechnoPark/Highload/http-test-suite/'
DEFAULT_PAGE = 'index.html'